// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB3uuqpJiJhHNX0EDd26zSJgDUuYgBWYc',
    appId: '1:459149840078:web:92da19322201819954ca9f',
    messagingSenderId: '459149840078',
    projectId: 'hallowed-winter-427307-p3',
    authDomain: 'hallowed-winter-427307-p3.firebaseapp.com',
    storageBucket: 'hallowed-winter-427307-p3.appspot.com',
    measurementId: 'G-X9GQ7EB52C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlSSvFr_9s4H4VQQNHvJ5FyUC1bsJEaYc',
    appId: '1:459149840078:android:ee87273cb84a552754ca9f',
    messagingSenderId: '459149840078',
    projectId: 'hallowed-winter-427307-p3',
    storageBucket: 'hallowed-winter-427307-p3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3X218NTeb5h3f61l4Yv5SY6JKKeRq4OU',
    appId: '1:459149840078:ios:ed3a16522f61ba3454ca9f',
    messagingSenderId: '459149840078',
    projectId: 'hallowed-winter-427307-p3',
    storageBucket: 'hallowed-winter-427307-p3.appspot.com',
    iosBundleId: 'com.example.goalMarker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3X218NTeb5h3f61l4Yv5SY6JKKeRq4OU',
    appId: '1:459149840078:ios:ed3a16522f61ba3454ca9f',
    messagingSenderId: '459149840078',
    projectId: 'hallowed-winter-427307-p3',
    storageBucket: 'hallowed-winter-427307-p3.appspot.com',
    iosBundleId: 'com.example.goalMarker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCB3uuqpJiJhHNX0EDd26zSJgDUuYgBWYc',
    appId: '1:459149840078:web:0e011fdef57738cd54ca9f',
    messagingSenderId: '459149840078',
    projectId: 'hallowed-winter-427307-p3',
    authDomain: 'hallowed-winter-427307-p3.firebaseapp.com',
    storageBucket: 'hallowed-winter-427307-p3.appspot.com',
    measurementId: 'G-NV9YCRPX88',
  );
}
